add new

diff --git a/portfolio-amplify/Jenkinsfile b/portfolio-amplify/Jenkinsfile
--- a/portfolio-amplify/Jenkinsfile
+++ b/portfolio-amplify/Jenkinsfile
@@ -2,46 +2,53 @@ pipeline {
     agent any
 
     environment {
-        IMAGE_NAME = "portfolio-app"
-        CONTAINER_NAME = "portfolio-app-container"
-        PORT = "3000"
+        DOCKER_IMAGE = "portfolio-app"
+        DOCKER_CONTAINER = "portfolio-container"
     }
 
     stages {
         stage('Checkout') {
             steps {
-                git https://github.com/omwarkri/portfolio-amplify.git
+                git branch: 'main',
+                    url: 'https://github.com/omwarkri/portfolio-amplify.git'
             }
         }
 
         stage('Build Docker Image') {
             steps {
-                sh "docker build -t ${IMAGE_NAME} ."
+                sh '''
+                    echo "🚀 Building Docker image..."
+                    docker build -t $DOCKER_IMAGE .
+                '''
             }
         }
 
-        stage('Stop & Remove Old Container') {
+        stage('Stop Old Container') {
             steps {
-                sh """
-                docker stop ${CONTAINER_NAME} || true
-                docker rm ${CONTAINER_NAME} || true
-                """
+                sh '''
+                    echo "🛑 Stopping old container if exists..."
+                    docker stop $DOCKER_CONTAINER || true
+                    docker rm $DOCKER_CONTAINER || true
+                '''
             }
         }
 
-        stage('Run Container') {
+        stage('Run New Container') {
             steps {
-                sh "docker run -d -p ${PORT}:3000 --name ${CONTAINER_NAME} ${IMAGE_NAME}"
+                sh '''
+                    echo "▶️ Starting new container..."
+                    docker run -d -p 3000:3000 --name $DOCKER_CONTAINER $DOCKER_IMAGE
+                '''
             }
         }
     }
 
     post {
         success {
-            echo "Deployment Successful! App running on port ${PORT}"
+            echo "✅ Deployment successful! Open: http://<192.168.153.131>:3000"
         }
         failure {
-            echo "Deployment Failed!"
+            echo "❌ Deployment failed. Check logs in Jenkins console."
         }
     }
 }
