add new

diff --git a/portfolio-amplify/Jenkinsfile b/portfolio-amplify/Jenkinsfile
--- a/portfolio-amplify/Jenkinsfile
+++ b/portfolio-amplify/Jenkinsfile
@@ -1,39 +1,47 @@
 pipeline {
     agent any
 
+    environment {
+        IMAGE_NAME = "portfolio-app"
+        CONTAINER_NAME = "portfolio-app-container"
+        PORT = "3000"
+    }
+
     stages {
         stage('Checkout') {
             steps {
-                git branch: 'main', url: 'https://github.com/omwarkri/portfolio-amplify.git'
+                git 'https://github.com/your-username/your-repo.git'
             }
         }
 
-        stage('Install Dependencies') {
+        stage('Build Docker Image') {
             steps {
-                sh 'npm install'
+                sh "docker build -t ${IMAGE_NAME} ."
             }
         }
 
-        stage('Build') {
+        stage('Stop & Remove Old Container') {
             steps {
-                sh 'npm run build'
+                sh """
+                docker stop ${CONTAINER_NAME} || true
+                docker rm ${CONTAINER_NAME} || true
+                """
             }
         }
 
-        stage('Test') {
+        stage('Run Container') {
             steps {
-                sh 'npm test || echo "No tests"'
+                sh "docker run -d -p ${PORT}:3000 --name ${CONTAINER_NAME} ${IMAGE_NAME}"
             }
         }
-        stage('Deploy') {
-    steps {
-        sh '''
-            nohup npm run start -- -p 3000 -H 0.0.0.0 > nextjs.log 2>&1 &
-        '''
-        echo "Next.js app is running at http://192.168.153.131:3000"
     }
-}
 
-
+    post {
+        success {
+            echo "Deployment Successful! App running on port ${PORT}"
+        }
+        failure {
+            echo "Deployment Failed!"
+        }
     }
 }
